"""
========================================================================================
DRACBV Generator Peaking Charts (current_model/ui/tab_dracbv_beta/charts.py)
========================================================================================

Description:
------------
Plotly visualization suite for the Generator Peaking Beta simulator:
  1. 15-Minute Load & Generation Timeseries:
     - Original Facility Demand (Baseline)
     - New Residual Grid Load (Post-Peaking)
     - Power Generated by Generator
     - Contracted Capacity / Trigger Limit (horizontal line)
  2. Cumulative Payment Series (Kumulierte Zahlungsreihe) Chart:
     - Cumulative Status Quo Grid Bill vs. Cumulative With Generator
"""

from typing import List, Dict, Any, Optional
import numpy as np
import pandas as pd
import plotly.graph_objects as go


def create_generator_dispatch_chart(
    df_dispatch: pd.DataFrame,
    trigger_kw: float,
    days_to_show: Optional[int] = None
) -> go.Figure:
    """
    Renders 15-minute electrical dispatch comparing Original Load, New Grid Load, and Generator Output.
    Supports viewing a custom slice or the complete full-duration period with interactive range slider.
    """
    fig = go.Figure()
    total_steps = len(df_dispatch)
    total_days = total_steps * 0.25 / 24.0

    if days_to_show is None or (days_to_show * 96) >= total_steps:
        steps_to_show = total_steps
        is_full = True
        title_text = f"<b>15-Minute Load Dispatch: Original vs. New Grid Load with Generator (Full Period: {total_days:.0f} Days / {total_steps:,} Intervals)</b>"
    else:
        steps_to_show = min(total_steps, days_to_show * 96)
        is_full = False
        title_text = f"<b>15-Minute Load Dispatch: Original vs. New Grid Load with Generator ({days_to_show} Days Sample)</b>"

    df_slice = df_dispatch.iloc[:steps_to_show].copy()
    x_axis = df_slice["timestamp"] if "timestamp" in df_slice.columns else np.arange(steps_to_show)

    # Use Scattergl for performance when rendering large multi-month/annual series
    scatter_cls = go.Scattergl if steps_to_show > 4000 else go.Scatter

    # 1. Original Facility Load (Baseline)
    fig.add_trace(scatter_cls(
        x=x_axis,
        y=df_slice["Original_Load_kW"],
        name="Facility Load (Baseline)",
        mode="lines",
        line=dict(color="#64748B", width=1.5, dash="dot"),
        hovertemplate="%{y:.1f} kW"
    ))

    # 2. Generator Power Output (Shaded area)
    fig.add_trace(scatter_cls(
        x=x_axis,
        y=df_slice["Generator_Power_kW"],
        name="Generator Power Output",
        mode="lines",
        line=dict(color="#F59E0B", width=1.8),
        fill="tozeroy",
        fillcolor="rgba(245, 158, 11, 0.25)",
        hovertemplate="%{y:.1f} kW"
    ))

    # 3. New Residual Grid Draw (Mitigated)
    fig.add_trace(scatter_cls(
        x=x_axis,
        y=df_slice["New_Grid_Load_kW"],
        name="New Grid Load (Post-Peaking)",
        mode="lines",
        line=dict(color="#10B981", width=2.0),
        hovertemplate="%{y:.1f} kW"
    ))

    # 4. Grid Limit / Trigger Line
    fig.add_hline(
        y=trigger_kw,
        line_dash="dash",
        line_color="#EF4444",
        line_width=2,
        annotation_text=f"Grid Limit / Trigger ({trigger_kw:.0f} kW)",
        annotation_position="top left",
        annotation_font_color="#EF4444"
    )

    fig.update_layout(
        title=title_text,
        xaxis_title="Time",
        yaxis_title="Active Power (kW)",
        template="plotly_dark",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(15,23,42,0.6)",
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        margin=dict(l=40, r=40, t=80, b=40),
        height=450,
        xaxis=dict(
            rangeslider=dict(visible=True if is_full or steps_to_show >= 96 * 30 else False)
        )
    )
    return fig


def create_cumulative_payment_chart(
    df_zahlungsreihe: pd.DataFrame,
    currency: str = "EUR"
) -> go.Figure:
    """
    Renders Cumulative Payment Schedule (Kumulierte Zahlungsreihe) comparing
    Status Quo (Grid Only) vs. With Generator over the billing timeline.
    """
    fig = go.Figure()

    months = df_zahlungsreihe["Month"].tolist()
    cum_base = df_zahlungsreihe["Cum_Status_Quo"].tolist()
    cum_gen = df_zahlungsreihe["Cum_With_Generator"].tolist()

    # 1. Status Quo Cumulative
    fig.add_trace(go.Scatter(
        x=months,
        y=cum_base,
        name="Status Quo (Grid Only - Baseline)",
        mode="lines+markers",
        line=dict(color="#EF4444", width=2.5),
        marker=dict(size=7),
        hovertemplate=f"%{{y:,.0f}} {currency}"
    ))

    # 2. With Generator Cumulative
    fig.add_trace(go.Scatter(
        x=months,
        y=cum_gen,
        name="With Generator (Grid + Genset OPEX)",
        mode="lines+markers",
        line=dict(color="#10B981", width=2.5),
        marker=dict(size=7),
        hovertemplate=f"%{{y:,.0f}} {currency}"
    ))

    fig.update_layout(
        title=f"<b>Cumulative Payment Trajectory (Kumulierte Zahlungsreihe) — Status Quo vs. Generator ({currency})</b>",
        xaxis_title="Billing Month",
        yaxis_title=f"Cumulative Cost ({currency})",
        template="plotly_dark",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(15,23,42,0.6)",
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        margin=dict(l=40, r=40, t=80, b=40),
        height=400
    )
    return fig
